author: eccentric_nz
description: The periodic table, elements, compounds and cool sciencey things in Minecraft
main: me.eccentric_nz.chemistry.Chemistry
name: Chemistry
load: POSTWORLD
version: 1.0.0
api-version: 1.14
#website: http://dev.bukkit.org/projects/chemistry
#dev-url: http://dev.bukkit.org/projects/chemistry
#url: http://dev.bukkit.org/projects/chemistry
permissions:
  chemistry.command:
    description: Allow a player to open Chemistry GUIs by command.
    default: op
  chemistry.creative:
    description: Allow a player to craft and open the Chemistry creative GUIs.
    default: op
  construct.build:
    description: Allow a player to craft and open the 'Element constructor' GUI.
    default: op
  compound.create:
    description: Allow a player to craft and open the 'Chemical compounds' GUI.
    default: op
  reducer.use:
    description: Allow a player to craft and open the 'Material reducer' GUI.
    default: op
  products.craft:
    description: Allow a player to craft and open the 'Product crafting' GUI.
    default: op
  lab.combine:
    description: Allow a player to craft and open the 'Lab table' GUI.
    default: op
  formula.show:
    description: Allow a player to view a compound or product formula.
    default: op
commands:
  chemistry:
    description: Open a Chemistry creative GUI.
    usage: /<command> [elements|compounds|lab|products]
    permission: chemistry.creative
    permission-message: You don't have the permission <permission> to use this command
  construct:
    description: Open the 'Chemical compounds' creation GUI.
    usage: /<command>
    permission: compound.create
    permission-message: You don't have the permission <permission> to use this command
  compound:
    description: Open the 'Chemical compounds' creation GUI.
    usage: /<command>
    permission: compound.create
    permission-message: You don't have the permission <permission> to use this command
  reduce:
    description: Open the 'Material reducer' GUI.
    usage: /<command>
    permission: reducer.use
    permission-message: You don't have the permission <permission> to use this command
  product:
    description: Open the 'Product crafting' GUI.
    usage: /<command>
    permission: product.craft
    permission-message: You don't have the permission <permission> to use this command
  lab:
    description: Open the 'Lab table' GUI.
    usage: /<command>
    permission: lab.combine
    permission-message: You don't have the permission <permission> to use this command
  formula:
    description: Show a compound or product formula.
    usage: /<command> [compound|product]
    permission: formula.show
    permission-message: You don't have the permission <permission> to use this command
